/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChooseAvatar: typeof import('./../../components/userInfo/ChooseAvatar.vue')['default']
    GetPhoneNumber: typeof import('./../../components/userInfo/GetPhoneNumber.vue')['default']
    Layout: typeof import('./../../components/layout/Layout.vue')['default']
    NavBar: typeof import('./../../components/layout/NavBar.vue')['default']
    NickName: typeof import('./../../components/userInfo/NickName.vue')['default']
    NutAnimate: typeof import('nutui-uniapp/components/animate/animate.vue')['default']
    NutAvatar: typeof import('nutui-uniapp/components/avatar/avatar.vue')['default']
    NutBadge: typeof import('nutui-uniapp/components/badge/badge.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutInput: typeof import('nutui-uniapp/components/input/input.vue')['default']
    NutToast: typeof import('nutui-uniapp/components/toast/toast.vue')['default']
    TabBar: typeof import('./../../components/layout/TabBar.vue')['default']
  }
}
